export enum ROUTES {
  GUEST_NAVIGATION = 'GUEST_NAVIGATION',
  APP_NAVIGATION = 'APP_NAVIGATION',
  LOADING_SCREEN = 'LOADING_SCREEN'
}

export enum GUEST_NAVIGATION {
  LOGIN = 'LOGIN',
}

export enum APP_NAVIGATION {
  HOME = 'HOME',
  SEARCH = 'SEARCH',
  DETAIL_ORDER = 'DETAIL_ORDER'
}